CREATE TABLE agent_auths (
	id UUID PRIMARY KEY,
	agent_id UUID NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
	name VARCHAR(100) NOT NULL,
	type VARCHAR(30) NOT NULL,
	config JSONB NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
	updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
	UNIQUE (agent_id, name)
);
CREATE INDEX idx_agent_auths_agent_id ON agent_auths(agent_id);
