CREATE TABLE intentions_meta (
	id UUID PRIMARY KEY,
	intention_id UUID NOT NULL REFERENCES intentions(id) ON DELETE CASCADE,
	key VARCHAR(60) NOT NULL,
	value JSONB,
	created_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
	updated_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
	UNIQUE (intention_id, key)
);
